### ISSUE TITLE
Multiple Constructors

### ISSUE THREAD

**Issue by Tlapr231** [RJStead/umpleTranslation#23]
Output:
Translate/CascadeDeleteC.java.txt - Syntax error at or near:
        ; } } public C >>> ( <<< B aB ) { myD

File : 
[CascadeDeleteC.java.txt](https://github.com/RJStead/umpleTranslation/files/9660381/CascadeDeleteC.java.txt)

**Comment by RJStead** [comment]
Multiple constructors is not fixed in certain cases.
Does not create a __init__ and creates the same function name twice.

Example file is MentorAF.java (umple/testbed/src-gen-umple/cruise/associations/MentorAF.java)
