### ISSUE TITLE
"".equals(x)

### ISSUE THREAD

**Issue by Tlapr231** [RJStead/umpleTranslation#27]
Output:
TXL0192E line 38 of Translate/ClassTemplateTest_CodeInjectionsParametersBasic.java.txt - Syntax error at or near:
        > 0 & & "" >>> . <<< equals ( b ) )

File : 
[ClassTemplateTest_CodeInjectionsParametersBasic.java.txt](https://github.com/RJStead/umpleTranslation/files/9660375/ClassTemplateTest_CodeInjectionsParametersBasic.java.txt)

**Comment by SamuelLabonte** [comment]
Fixed this in a recent commit. However the file in question has some funky Java. A string seems to be concatenating to a var without a +? Not sure if that's valid or what's going on there.

**Comment by SamuelLabonte** [comment]
Made another fix. These should now be translated to == statements
