### ISSUE TITLE
String[] as argument of function

### ISSUE THREAD

**Issue by Tlapr231** [RJStead/umpleTranslation#28]
Output:
[Translate/ClassTemplateTest_Generated.java.txt, umpleJavaToPython.txl] : TXL0192E line 27 of Translate/ClassTemplateTest_Generated.java.txt - Syntax error at or near:
        static void main ( String >>> [ <<< ] args ) { Thread

File : 
[ClassTemplateTest_Generated.java.txt](https://github.com/RJStead/umpleTranslation/files/9660374/ClassTemplateTest_Generated.java.txt)

**Comment by Tlapr231** [comment]
Similar error with :
[Academy.java.txt](https://github.com/RJStead/umpleTranslation/files/9840400/Academy.java.txt)
[Business.java.txt](https://github.com/RJStead/umpleTranslation/files/9842124/Business.java.txt)
[Client.java.txt](https://github.com/RJStead/umpleTranslation/files/9842194/Client.java.txt)
[Ellipse.java.txt](https://github.com/RJStead/umpleTranslation/files/9842654/Ellipse.java.txt)
[HelloWorld.java.txt](https://github.com/RJStead/umpleTranslation/files/9842658/HelloWorld.java.txt)
[Main.java.txt](https://github.com/RJStead/umpleTranslation/files/9842664/Main.java.txt)
[PhoneSystemSimulation.java.txt](https://github.com/RJStead/umpleTranslation/files/9842673/PhoneSystemSimulation.java.txt)
[DigitalWatch.java.txt](https://github.com/RJStead/umpleTranslation/files/9842681/DigitalWatch.java.txt)

**Comment by SamuelLabonte** [comment]
Most of these files have features we are not supporting. The only two that are valid are Ellipse.java and Buisness.java . ClassTemplateTest_Generated.java.txt has multithreading. All others have a main function, which means user generated code.
