### ISSUE TITLE
Throws

### ISSUE THREAD

**Issue by Tlapr231** [RJStead/umpleTranslation#35]
Output:
[Translate/Class_DistributableRMI5_IUmpleObjectFactory.java.txt, umpleJavaToPython.txl] : TXL0192E line 15 of Translate/Class_DistributableRMI5_IUmpleObjectFactory.java.txt - Syntax error at or near:
        public void stopNode ( ) >>> throws <<< RemoteException ; public IClientImpl createClient

File : 
[Class_DistributableRMI5_IUmpleObjectFactory.java.txt](https://github.com/RJStead/umpleTranslation/files/9660353/Class_DistributableRMI5_IUmpleObjectFactory.java.1.txt)

**Comment by RJStead** [comment]
Java throws code:


Python throws example:
raise Exception("Sorry, no numbers below zero")
