### ISSUE TITLE
Try

### ISSUE THREAD

**Issue by Tlapr231** [RJStead/umpleTranslation#36]
Output:
[Translate/Class_DistributableRMI5_UmpleObjectFactory.java.txt, umpleJavaToPython.txl] : TXL0127E input file 'Translate/Class_DistributableRMI5_UmpleObjectFactory.java.txt' - Parse time limit (26600000 cycles) exceeded
[Translate/Class_DistributableRMI5_UmpleObjectFactory.java.txt, umpleJavaToPython.txl] : TXL0192E line 53 of Translate/Class_DistributableRMI5_UmpleObjectFactory.java.txt - Syntax error at or near:
        input = null ; try >>> { <<< input = new FileInputStream (

File : 
[Class_DistributableRMI5_UmpleObjectFactory.java.txt](https://github.com/RJStead/umpleTranslation/files/9660347/Class_DistributableRMI5_UmpleObjectFactory.java.txt)

**Comment by RJStead** [comment]
[TryFiles.zip](https://github.com/RJStead/umpleTranslation/files/10004998/TryFiles.zip)

**Comment by Tlapr231** [comment]
All Trys are passing but finally is not handled. Will open another issue
