### ISSUE TITLE
Hashcode

### ISSUE THREAD

**Issue by Tlapr231** [RJStead/umpleTranslation#38]
Output:
[Translate/EqualsTest_AlreadyImmutable.java.txt, umpleJavaToPython.txl] : TXL0127E input file 'Translate/EqualsTest_AlreadyImmutable.java.txt' - Parse time limit (26600000 cycles) exceeded
[Translate/EqualsTest_AlreadyImmutable.java.txt, umpleJavaToPython.txl] : TXL0192E line 118 of Translate/EqualsTest_AlreadyImmutable.java.txt - Syntax error at or near:
        getDoubleId ( ) ) ) >>> . <<< hashCode ( ) ; cachedHashCode

RJ : Idea: use the .hash function

File : [EqualsTest_AlreadyImmutable.java.txt](https://github.com/RJStead/umpleTranslation/files/9660342/EqualsTest_AlreadyImmutable.java.txt)

**Comment by SamuelLabonte** [comment]
Should also translate the hashcode method name to `__hash__`

**Comment by Tlapr231** [comment]
I ran this previously failling example and it actually works

**Comment by SamuelLabonte** [comment]
Did not yet fix the full problem, .hashCode() is not a thing in python
