### ISSUE TITLE
Function are being translated when they should not be touched

### ISSUE THREAD

**Issue by Tlapr231** [RJStead/umpleTranslation#39]
When Function are generated in umple usually, they are completely ignored by the translator. However the python generator is translating the function

For example : 
for this umple file
```
class A {
  func() Java {
   do not edit this code
   print(Java);
  }
  
  func() Python {
    do not edit this code
    print(Python);
  }
} 
```
Java generates this :

```
// line 1 "A.ump"
public class A
{

  //------------------------
  // MEMBER VARIABLES
  //------------------------

  //------------------------
  // CONSTRUCTOR
  //------------------------

  public A()
  {}

  //------------------------
  // INTERFACE
  //------------------------

  public void delete()
  {}

  // line 3 "A.ump"
  public void func(){
    do not edit this code
    print(Python);
  }

}
```
Notice that the function is not even touched (and is saying python because it is the in between file for python translation)

But for the python generated code it looks like this : 
```
class A:
    def __init__(self):
        pass

    def delete(self):
        pass

    def func(self):
        do
        not
        edit
        this
        code self.print(Python);
```
Notice that "do not edit this" has moved and "self." has been added to the print

**Comment by SamuelLabonte** [comment]
Tags need to be added so the TXL can ignore whatever is in them
