### ISSUE TITLE
Converting equals function for objects

### ISSUE THREAD

**Issue by RJStead** [RJStead/umpleTranslation#43]
The equals function in Java is defined in the language, however this is not the case in Python. The Python equivalent is == in our case, so it should change the line to include an ==.

The following code was observed in the auto-generated testbed file ProgramAI.py and ProgramAI.java

Java line:
`if (!equals(existingProgram))`

Python line:
`if not self.equals(existingProgram) :`

**Comment by SamuelLabonte** [comment]
Should have been fixed in recent commit. The translation however will use the __eq__ and not == to simply things txl wise
