### ISSUE TITLE
Ternary operator wrong translation

### ISSUE THREAD

**Issue by SamuelLabonte** [RJStead/umpleTranslation#48]
Some ternary operators in toStrings() are not being translated to equivalent python, causing different results in both languages
[OneSymmetric.txt](https://github.com/RJStead/umpleTranslation/files/9862851/OneSymmetric.txt)

**Comment by Tlapr231** [comment]
This appears to be fixed. see below
[output.py.txt](https://github.com/RJStead/umpleTranslation/files/10025556/output.py.txt)
