### ISSUE TITLE
Static Variable are not set properly

### ISSUE THREAD

**Issue by MainvilleYanic** [RJStead/umpleTranslation#53]
Static variables are not set properly. They are transformed into instance variables, when they are transformed correctly.
Exemple:
[TestClass.java.txt](https://github.com/RJStead/umpleTranslation/files/9963984/TestClass.java.txt)
Should give:
[TestClass_expected.py.txt](https://github.com/RJStead/umpleTranslation/files/9963991/TestClass_expected.py.txt)
but actually is:
[TestClass_actual.py.txt](https://github.com/RJStead/umpleTranslation/files/9963993/TestClass_actual.py.txt)

**Comment by Tlapr231** [comment]
This is tested. See new output
[output.py.txt](https://github.com/RJStead/umpleTranslation/files/10025527/output.py.txt)

**Comment by RJStead** [comment]
[ConstDefault.zip](https://github.com/RJStead/umpleTranslation/files/10087195/ConstDefault.zip)
