### ISSUE TITLE
Dictionary translation

### ISSUE THREAD

**Issue by SamuelLabonte** [RJStead/umpleTranslation#57]
Dictionaries are not yet translated. I do not have specific files at the moment, but I remember that some many to many relations create functions that use dicts.

Example Co-op system in umple online generates java that has hashmaps

**Comment by MainvilleYanic** [comment]
[DictionnaryExample.zip](https://github.com/RJStead/umpleTranslation/files/10004305/DictionnaryExample.zip)
These files use Dictionaries.

**Comment by Tlapr231** [comment]
Files are now passing (or having different problems)

**Comment by MainvilleYanic** [comment]
The files are passing, but the translation doesn't occur (the generated code is still Java)... see linked files for examples.
