### ISSUE TITLE
function and array stops translation

### ISSUE THREAD

**Issue by MainvilleYanic** [RJStead/umpleTranslation#61]
Problem: String them = compareTo.getStringListIds()[i];

Umple Code:
[UmpleCode.ump.txt](https://github.com/RJStead/umpleTranslation/files/9993613/UmpleCode.ump.txt)

Java Code:
[JavaCode.java.txt](https://github.com/RJStead/umpleTranslation/files/9993614/JavaCode.java.txt)

TXL Error:
[Translate/JavaCode.java, umpleJavaToPython.txl] : TXL0127E input file 'Translate/JavaCode.java' - Parse time limit (26600000 cycles) exceeded
[Translate/JavaCode.java, umpleJavaToPython.txl] : TXL0192E line 198 of Translate/JavaCode.java - Syntax error at or near:
	me = getStringListIds ( ) >>> [ <<< i ] ; String them

**Comment by Tlapr231** [comment]
I am still getting this issue 

command : txl -l ./txl/umpleJavaToPython.ctxl Student.java -o ./output.py -s 2000

error : 
[./txl/umpleJavaToPython.ctxl] : TXL0911W - (Warning) Stack limit less than recommended for TXL size (probable cause: shell stack limit)
[./txl/umpleJavaToPython.ctxl] : TXL0913I - (Information) Recursion stack limit reduced from 102400000 to 7340032 to fit
TXL v10.8b (13.7.22) (c) 1988-2022 Queen's University at Kingston
Loading ./txl/umpleJavaToPython.ctxl ...
Parsing Student.java ...
[Student.java, umpleJavaToPython.txl] : TXL0127E input file 'Student.java' - Parse time limit (500000000 cycles) exceeded
[Student.java, umpleJavaToPython.txl] : TXL0192E line 198 of Student.java - Syntax error at or near:
        me = getStringListIds ( ) >>> [ <<< i ] ; String them\

file : 
[Student.java.txt](https://github.com/RJStead/umpleTranslation/files/10072285/Student.java.txt)

**Comment by SamuelLabonte** [comment]
Works fine on my end. Probably something on your end. Are you running this with the right TXL?
