### ISSUE TITLE
(A) Replace UmpleOnline toString message

### ISSUE THREAD

**Issue by Tlapr231** [RJStead/umpleTranslation#62]
New output should be : 
"Generated Python is currently in beta. For more information please click here"

Also add a user manual page (in the Generators group) that explains the current limitations. In the output, add a <br/> after the above.

**Comment by MainvilleYanic** [comment]
Done

**Comment by MainvilleYanic** [comment]
Actually, needs to add limitations
https://github.com/umple/umple/wiki/Python-Generation-Limitation
