### ISSUE TITLE
Finally

### ISSUE THREAD

**Issue by Tlapr231** [RJStead/umpleTranslation#69]
Finally on a try catch is not being handled

Error : 
TXL v10.8b (13.7.22) (c) 1988-2022 Queen's University at Kingston
Loading ./txl/umpleJavaToPython.ctxl ...
Parsing .\Class_DistributableRMI5_UmpleObjectFactory.java.txt ...
[.\Class_DistributableRMI5_UmpleObjectFactory.java.txt, umpleJavaToPython.txl] : TXL0127E input file '.\Class_DistributableRMI5_UmpleObjectFactory.java.txt' - Parse time limit (26600000 cycles) exceeded
[.\Class_DistributableRMI5_UmpleObjectFactory.java.txt, umpleJavaToPython.txl] : TXL0192E line 68 of .\Class_DistributableRMI5_UmpleObjectFactory.java.txt - Syntax error at or near:
        location ) ; } finally >>> { <<< if ( input != null

[Class_DistributableRMI5_UmpleObjectFactory.java.txt](https://github.com/RJStead/umpleTranslation/files/10072327/Class_DistributableRMI5_UmpleObjectFactory.java.txt)
[UmpleRuntime.java.txt](https://github.com/RJStead/umpleTranslation/files/10072329/UmpleRuntime.java.txt)

**Comment by SamuelLabonte** [comment]
This seems to be runtime related. This is all probably out of scope
